Show error when unsupported video type is selected.
xwp/wp-core-media-widgets pull request #172
Opened 2017-05-10 20:51 UTC by timmyc

This branch seeks to inform users that certain video file types are not supported via the `renderPreview()` in the widget itself.  The `.mov` issue detailed in #171 is a bit complex - and until uploads can be properly restricted ( #128 ) - users will still be able to upload a .mov file which will not function properly when the widget is rendered on the front-end of the site.

So this branch is implementing @jasmussen 's [idea](https://github.com/xwp/wp-core-media-widgets/issues/171#issuecomment-300549660) - to not render a functioning `<video />` preview in the widget for a file type that we know will not work.  I borrowed @obenland's error message suggestion:

<img width="263" alt="customize__wordpress_develop_ _just_another_wordpress_site" src="https://cloud.githubusercontent.com/assets/22080/25920752/cdd0acc8-3587-11e7-8727-4cf879feda87.png">

__To Test__
- Create a video widget using a supported file type ( .webm, .m4v etc ) verify that the preview renders as expected
- Create a video widget using a .mov file, and verify the preview renders with an error message

2017-05-10 21:01 UTC, melchoyce commented
Looks good 👍 

Can we tighten up the padding inside the notice code blocks to `padding: 0 3px 0 0px;`?

<img width="286" alt="screen shot 2017-05-10 at 4 58 13 pm" src="https://cloud.githubusercontent.com/assets/2846578/25921126/4bcf9c32-35a2-11e7-8500-7a626aed34bb.png">

Should "movie" be "video?"

2017-05-10 21:11 UTC, timmyc commented
Thanks for testing it out @melchoyce - addressed the verbiage and padding in 23eaa1b

2017-05-10 21:14 UTC, westonruter approved these changes

2017-05-10 21:19 UTC, obenland requested changes

2017-05-10 21:19 UTC, obenland commented on wp-includes/widgets/class-wp-widget-media-video.php
> +			'unsupported_file_type' => sprintf( __( 'Sorry, we can\'t display the video file type selected. Please upload a file with one of these extensions instead: %1$s' ), '<code>.' . implode( '</code>, <
`can\'t` should be `can&#8217;t`, I cut corners in my example

2017-05-10 21:26 UTC, timmyc commented on wp-includes/widgets/class-wp-widget-media-video.php
> +			'unsupported_file_type' => sprintf( __( 'Sorry, we can\'t display the video file type selected. Please upload a file with one of these extensions instead: %1$s' ), '<code>.' . implode( '</code>, <
Changed it up in 76783bc

2017-05-10 21:35 UTC, obenland approved these changes

2017-05-10 21:38 UTC, merged

2017-05-11 05:23 UTC, jasmussen commented
💖